# Workflow to run integration tests with SpinW using Matlab-Actions

name: Runs integration test for Brille-SpinW

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Python
              uses: actions/setup-python@v1
              with:
                python-version: 3.7

            - name: Install dependencies
              id: deps
              run: |
                python -m pip install --upgrade pip
                python -m pip install numpy
                git submodule update --init
                git clone https://github.com/mducle/spinw --branch brille_integration --depth 1
                git clone https://github.com/brille/brille brille_src --depth 1
                #cd brille_src && python setup.py install

            # Need a manylinux wheel - else get ABI error
            - name: Build Brille manylinux wheel
              uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
              with:
                python-versions: 'cp37-cp37m'
                build-requirements: 'cmake'
                system-packages: ''
                package-path: 'brille_src'
                pip-wheel-args: '--no-deps'

            - name: Install Brille wheel
              run: |
                python -m pip install wheelhouse/brille*-cp37-cp37m-*manylinux2010_x86_64.whl

            - name: Install Matlab
              uses: matlab-actions/setup-matlab@v1

            - name: Run tests
              uses: matlab-actions/run-command@v1
              with:
                command: addpath('test'), run_tests()

            - name: Create release
              uses: matlab-actions/run-command@v1
              with:
                command: release()

            - name: Upload mltbx
              uses: actions/upload-artifact@v2
              with:
                name: Brillem Toolbox
                path: mltbx/brillem.mltbx
              
